### ISSUE TITLE
Exception in thread "main" java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by rgeos** [takezoe/predictionio-template-automl#10]
When following the instructions, the command `pio train` will lead to the following exception:
```
Exception in thread "main" java.lang.AbstractMethodError
        at org.apache.spark.ml.param.Params$class.$init$(params.scala:868)
        at com.salesforce.op.stages.impl.tuning.Splitter.<init>(Splitter.scala:47)
        at com.salesforce.op.stages.impl.tuning.DataSplitter.<init>(DataSplitter.scala:62)
        at com.salesforce.op.stages.impl.tuning.DataSplitter$.apply(DataSplitter.scala:51)
        at com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector$.withCrossValidation$default$1(BinaryClassificationModelSelector.scala:159)
        at com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector$.apply(BinaryClassificationModelSelector.scala:134)
        at org.example.vanilla.Algorithm.train(Algorithm.scala:113)
        at org.example.vanilla.Algorithm.train(Algorithm.scala:94)
        at org.apache.predictionio.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:49)
        at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
        at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at org.apache.predictionio.controller.Engine$.train(Engine.scala:690)
        at org.apache.predictionio.controller.Engine.train(Engine.scala:176)
        at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
        at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:251)
        at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by takezoe** [comment]
This would help you. https://github.com/salesforce/TransmogrifAI/issues/369

**Comment by rgeos** [comment]
@takezoe thank you for the link, however after a successful `pio build`,

The recommended setup of

| java | transmogrifai | spark | scala |
| --- | --- | --- | --- |
| 1.8 | 0.6.0 | 2.3.2 | 2.11.12 |

Will return the following error at `pio train`:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.ParserUtil$.quote(Ljava/lang/String;Lorg/json4s/Formats;)Ljava/lang/String;
        at org.json4s.native.JsonMethods$$anonfun$3.apply(JsonMethods.scala:43)
        at org.json4s.native.JsonMethods$$anonfun$3.apply(JsonMethods.scala:43)
        at scala.collection.immutable.List.map(List.scala:273)
        at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:43)
        at org.json4s.native.JsonMethods$.render(JsonMethods.scala:63)
        at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2$$anonfun$2.apply(WorkflowUtils.scala:177)
        at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2$$anonfun$2.apply(WorkflowUtils.scala:168)
        at scala.Option.map(Option.scala:146)
        at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2.apply(WorkflowUtils.scala:168)
        at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2.apply(WorkflowUtils.scala:159)
        at scala.Option.map(Option.scala:146)
        at org.apache.predictionio.workflow.WorkflowUtils$.getParamsFromJsonByFieldAndClass(WorkflowUtils.scala:159)
        at org.apache.predictionio.controller.Engine.jValueToEngineParams(Engine.scala:363)
        at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:222)
        at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

While this setup 

| java | transmogrifai | spark | scala |
| --- | --- | --- | --- |
| 1.8 | 0.6.0 | 2.4.0 | 2.11.12 |

will return the same as https://github.com/takezoe/predictionio-template-automl/issues/10#issue-489557674 at `pio train`

This is how my `build.sbt` file looks like:

```scala
name := "template-scala-automl"

scalaVersion := "2.11.12"
val sparkV = "2.3.2"
val aiV = "0.6.0"

libraryDependencies ++= Seq(
  "org.apache.predictionio" %% "apache-predictionio-core" % "0.14.0" % "provided",
  "org.apache.spark"        %% "spark-mllib"              % sparkV % "provided",
  "com.salesforce.transmogrifai" %% "transmogrifai-core" % aiV excludeAll(
    ExclusionRule(organization = "org.apache.spark")
  ),
  "com.salesforce.transmogrifai" %% "transmogrifai-local" % aiV excludeAll(
    ExclusionRule(organization = "org.apache.spark")
  ),
  "com.salesforce.transmogrifai" %% "transmogrifai-features" % aiV  excludeAll(
    ExclusionRule(organization = "org.apache.spark")
  ),
  "org.scalatest"           %% "scalatest"                % "3.0.5" % "test")

parallelExecution in Test := false

assemblyMergeStrategy in assembly := {
  case "META-INF/MANIFEST.MF" => MergeStrategy.discard
  case "reference.conf"       => MergeStrategy.concat
  case _                      => MergeStrategy.first
}
```

This is my java -version
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by rgeos** [comment]
I've managed to make it work with the following setup:

java | transmogrifai | spark | scala | pio 
-- | -- | -- | -- | --
1.8 | 0.6.0 | 2.3.1 | 2.11.12 |  0.14.0

PredictionIO must be compiled with the following command:
`./make-distribution.sh -Dscala.version=2.11.12 -Dspark.version=2.3.1`

**Comment by takezoe** [comment]
I see. Could you create a pull request to update `build.sbt` as yours?
